### ISSUE TITLE
Installation from source fails

### ISSUE THREAD

**Issue by h836472** [pmelsted/bifrost#58] opened 2022-01-25 16:00 UTC
Dear Bifrost Developers,

Compilation and install of bifrost from source code fails as walk trough the lists of commands provided in the manual:

_git clone https://github.com/pmelsted/bifrost.git
cd bifrost && mkdir build && cd build
cmake ..
make
make install_

when calling command "make install", the installation script fails with the following error message:

_-- Installing: /usr/local/include/bifrost/UnitigIterator.tcc
-- Installing: /usr/local/include/bifrost/UnitigMap.tcc
CMake Error at src/cmake_install.cmake:126 (FILE):
  file INSTALL cannot find "/SSD8/root/install/bifrost/src/xxhash.c".
Call Stack (most recent call first):
  cmake_install.cmake:37 (INCLUDE)
make: *** [install] Error 1_

Indeed, there is no trace of any xxhash.c file in the src folder. Can you please help me with this issue?

With kind regards,

Balazs Balint

**Comment by GuillaumeHolley** [comment] 2022-01-25 16:20
Dear @h836472,

Thank you for noticing, this issue was caused by a line in one of the Cmake file that should have deleted in a previous release. This is normally fixed in the latest commit, do a `git pull` and make sure to delete your `build` directory for a clean install.

Let me know if the issue is fixed for you.

Guillaume

**Comment by GuillaumeHolley** [comment] 2022-01-25 18:10
Good to know :) Closing now.

**Closed by GuillaumeHolley** 2022-01-25 18:10 UTC
