### ISSUE TITLE
Conda/Bifrost 1.0.3 illegal instruction error

### ISSUE THREAD

**Issue by ptrebert** [pmelsted/bifrost#20] opened 2020-05-14 15:00 UTC
Hi,
just fyi, after installing Bifrost via Conda/bioconda, it immediately exits with an "illegal instruction" error. Building from source on the same server is possible, though. The machine is equipped with the following CPU model:

```
model name      : Intel(R) Xeon(R) CPU E7-8857 v2 @ 3.00GHz
stepping        : 7
microcode       : 0x715
[...]
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
```

Best,
Peter

**Comment by GuillaumeHolley** [comment] 2020-05-14 16:12
Hi @ptrebert,

Thanks for letting me know about this issue. When you installed Bifrost with Conda, did you run it afterwards on the same machine (the one used for the Conda install) or a different one?

Guillaume

**Comment by ptrebert** [comment] 2020-05-14 16:41
Hi Guillaume,
yes, all steps were executed on the same machine.

Peter

**Comment by GuillaumeHolley** [comment] 2020-05-15 08:52
Hi @ptrebert,

"Illegal instructions" is usually an error occurring when you compile the program on machine A and execute it on machine B. By default, Bifrost compiles with "-march=native" as compile option, meaning it can optimize the code for the architecture it is compiled on. By executing on a different machine, the architecture might be different, hence the "Illegal instructions". Anyway, as you are compiling and executing on the same machine, this doesn't seem to be the issue.

Surely the source of the problem is that Bifrost uses AVX2 instructions for the construction **only when** they are available available (hence the "-march=native"). Normally, using AVX2 instructions should be deactivated for your CPU (I see your CPU is limited to AVX) but for some reasons, it is possible that it is still activated. Hence, Bifrost tries to use AVX2 instructions while you don't have them available. How would that be possible? Honestly, I don't know. I would say "probably a Conda issue" as the source install version worked just fine but I don't want to blame anyone else than me for now :) I will look into it.

**Comment by ptrebert** [comment] 2020-05-15 11:00
Hi Guillaume,
thanks for all your feedback, and, yes, I agree, machine incompatibility is the most likely explanation; where this is coming from in cases like this is also unclear to me (I had the same issue already with Racon). So my expectation was clearly not that you fix that right away, but rather that it shouldn't go unnoticed, in case other users run into the same problem - or, of course, somebody finds this issue by chance and has a solution :)
Best,
Peter

**Comment by winni2k** [comment] 2020-05-15 14:59
Conda installs precompiled binaries, so I would expect that if you want to distribute a conda package of bifrost without avx2 support, then you need to turn off avx2 support during compilation of the conda package (that is, in the bioconda recipe). I haven't found a package that does this yet, but I would guess numpy or tensorflow would have similar issues.

**Comment by GuillaumeHolley** [comment] 2020-05-15 15:09
I should have done that some time ago: I will add an extra option in the Cmake for AVX2: OFF to deactivate, ON to activate or NATIVE to have it ON if AVX2 is available. I'm not sure if there is a way to modify the conda recipe in a way that the end user would be able to choose one of these options when installing. But once again, installing Bifrost from source is rather straightforward so I really think the conda package is a waste of time.

**Comment by GuillaumeHolley** [comment] 2020-05-16 12:21
Hey @ptrebert and @winni2k,

I added two options to the cmake file:
- `-DENABLE_NATIVE_ARCH=ON/OFF` to enable/disable native compilation (`-march=native`). Default is `ON`.
- `-DENABLE_AVX2=ON/OFF` to enable/disable AVX2 instructions. Default is `ON`.

Those options are now explained in the README file and I also updated the Troubleshooting section with the `Illegal instruction` error.

**Comment by winni2k** [comment] 2020-05-19 10:06
I found a [user question on SO](https://stackoverflow.com/questions/47068709/your-cpu-supports-instructions-that-this-tensorflow-binary-was-not-compiled-to-u) about AVX2, etc. being disabled in the pip version of tensorflow. 

I think one workaround would be to create two packages: one with native compilation disabled, and one with lots of extensions enabled. In the mean-time, I think it's probably fine just to push the version without native extensions to bioconda so that users have a stable version that they can easily install and use.

**Comment by GuillaumeHolley** [comment] 2020-05-24 18:17
The main pro of Bioconda is in my opinion that it makes the install easy. How easy in this case? Well, not much easier than the source install (which has no dependency). Based on this, I'm not sure I want to disable native compilation and AVX2 instructions, which bring a nice speed up to the software, for an install which is going to be a little bit easier. Another thing that bothers me here is that large k-mers (k>31) is a compile time variable that cannot be changed with Bioconda, so anyone that works with k>31 will have to use the source install anyway.

**Comment by winni2k** [comment] 2020-05-24 21:18
I can see where you're coming from. If it's easy to compile, isn't that as easy to install as a conda package? I don't think that's the case, and there's some research by [Serghei Manghul](https://journals.plos.org/plosbiology/article?rev=2&id=10.1371/journal.pbio.3000333) that backs me up on this. However, you don't need to worry about conda packaging if you don't want to. Bifrost is available on a permissive licence, and sooner or later someone who cares enough will fix the bioconda recipe for the bioinformatics community.

**Comment by winni2k** [comment] 2020-05-25 07:07
I did a bit more reading on the state of native support in conda. On bioconda-recipes there's an [open thread on the subject](https://github.com/bioconda/bioconda-recipes/issues/2354), and a few more closed ones. It appears that native compilation has been an on-going subject of discussion in the conda community, and conda has so far defaulted to wide-ranging compatibility by only assuming an x86-64 architecture. 

There is something called build variants in conda, and there's this package that appears to provide a path for supplying multiple binaries for different cpu architectures: https://github.com/jjhelmus/selectable_pkg_variants_example

**Comment by winni2k** [comment] 2020-05-25 09:08
Regarding the compile-time kmer size definition, this issue exists in [McCortex](https://github.com/mcveanlab/mccortex) as well. There, the solution is to built a kmer specific binary for a kmer size of interest (e.g. `mccortex31`). There is a shell script included with mccortex that selects the correct binary at run time (i.e. 'mccortex <kmer_size> [mccortex_args...]`). 

For conda packaging, the [bioconda recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/mccortex/build.sh) simply compiles a few binaries for a range of kmer sizes and includes them in the package. That seems to take care of most people's (i.e. my) requirements.

**Comment by GuillaumeHolley** [comment] 2020-05-29 16:35
Hi @winni2k,

Thanks for all these information. I get your point regarding bioconda and the community fixing recipes. Yet, I feel very responsible for these recipes. If I just keep updating the source and no one update the recipes, people will end up using deprecated or buggy versions of Bifrost. So it's not that I don't want to take care of it, I really do but I'm lacking time for it. But hey, no one said that maintaining software was easy :)

Thank you for your link on the bioconda meta-packages, it seems to be the best solution at the moment for the problem at hand and I will probably do something like that for the next recipe update.

Thanks for the tip with McCortex. There is also BCALM2 which you can precompile for a range of k-mer sizes at first and the software will take care at run time of picking the right data structures/libraries. The thing is that for Bifrost, I would like some solution I could include directly in the API. It feels that it would be possible with a major refactoring. The idea (maybe naive) is that the MAX_KMER_SIZE parameter is mostly used in the type Kmer as a static variable. Type Kmer is currently exposed to the user in the API (some functions take as argument or return objects of type Kmer). By taking it or return strings/char arrays instead, this type would be used only internally by Bifrost and there, I would have the freedom of having something more complicated where the k-mer size would not be a static parameter anymore. It would be simpler for the user, no additional compile parameter, but the code of Bifrost would be more complex.

**Comment by ptrebert** [comment] 2020-05-29 17:16
Though I don't have anything to add in particular about Conda recipes and related build issues, I leave the below code snippets here for people who want to automatically install Bifrost on various infrastructure potentially supporting the AVX2 extension (and cannot wait for appropriate builds being available in a Conda channel :wink: ).

I use the following Conda environment (simpler specifications would likely work as well) as part of a Snakemake pipeline, and the setup works just fine inside this environment:

```
name: compile
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.6
  - pip=20.1.1
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - binutils-meta=1.0.4=0
  - binutils_impl_linux-64=2.34=h53a641e_2
  - binutils_linux-64=2.34=hc952b39_20
  - c-compiler=1.0.4=h516909a_0
  - cmake=3.17.0=h28c56e5_0
  - compilers=1.0.4=0
  - cxx-compiler=1.0.4=hc9558a2_0
  - fortran-compiler=1.0.4=he991be0_0
  - gcc_impl_linux-64=7.5.0=hd420e75_6
  - gcc_linux-64=7.5.0=h09487f9_20
  - gfortran_impl_linux-64=7.5.0=hdf63c60_6
  - gfortran_linux-64=7.5.0=h09487f9_20
  - glib=2.64.3=h6f030ca_0
  - gxx_impl_linux-64=7.5.0=hdf63c60_6
  - gxx_linux-64=7.5.0=h09487f9_20
  - ld_impl_linux-64=2.34=h53a641e_2
  - libblas=3.8.0=16_openblas
  - libcblas=3.8.0=16_openblas
  - libclang=9.0.1=default_hde54327_0
  - libcurl=7.69.1=hf7181ac_0
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.5.0=hdf63c60_6
  - liblapack=3.8.0=16_openblas
  - libllvm9=9.0.1=he513fc3_1
  - libopenblas=0.3.9=h5ec1e0e_0
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - llvm-openmp=10.0.0=hc9558a2_0
  - pkg-config=0.29.2=h516909a_1006
  - pthread-stubs=0.4=h14c3975_1001
  - xz=5.2.5=h516909a_0
  - zlib=1.2.11=h516909a_1006
```

Just following the setup instructions and running  `cmake -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX .. && make && make install` installs the Bifrost binary into the Conda environment, i.e., Bifrost is available in `$PATH` after activating the Conda environment.

**Comment by winni2k** [comment] 2020-05-30 06:47
This is really cool @ptrebert! Thanks for sharing! I might start doing this kind of thing in some of my snakemake rules with other tools that would benefit from native compilation.

**Comment by winni2k** [comment] 2020-05-30 07:01
@GuillaumeHolley I'd be happy to tinker with the bifrost package on bioconda for you, I just don't want to make a decision on this for you given how much you are invested in the code ;)

Of the options described above, how would you like the bioconda package to proceed? I would recommend two steps. First, fixing the installation problems by making the `bifrost` package be compiled with `-march=x86-64`. This will slow things down, but at least guarantee that the package is installable by everyone. 

Next, I can take a closer look at https://github.com/jjhelmus/selectable_pkg_variants_example and see if I can apply the recommendations therein.

@GuillaumeHolley, would it be possible for you to create a flag in the cmake file that allows the direct setting of the `-march` argument during compilation?

**Comment by GuillaumeHolley** [comment] 2020-06-03 22:30
Hey @winni2k,

Sorry for the delay. I have changed the cmake option `-DENABLE_NATIVE_ARCH` into `-DCOMPILATION_ARCH`:
- Default is native compilation (`-march=native`) with `-DCOMPILATION_ARCH=native`.
- Bioconda can use the option `-DCOMPILATION_ARCH=x86-64` (any `-march=` argument will work).
- Disabling any form of architecture optimization is `DCOMPILATION_ARCH=OFF` (basically remove the `-march=` from the list of compilation options.

Let me know if that works for you ;)

**Comment by winni2k** [comment] 2020-06-04 07:50
Great! I'll change the bifrost bioconda recipe to use `-march=x86-64` for now.

We should discuss what else to do. I have read through https://github.com/jjhelmus/selectable_pkg_variants_example a bit more, and it appears that this solution requires the user to select an optimization version during installation (i.e. `bifrost` or `bifrost-skylake`) based on the CPU that they are running. @ptrebert, would that kind of thing work for your use case? Because it sounds like you are installing on a range of architectures and don't really know which one you happen to be on during installation?

**Comment by ptrebert** [comment] 2020-06-04 08:04
@winni2k 
Of course, I can only speak for myself/the infrastructure I am using, but heterogeneous architectures are often encountered in cluster environments, where different architectures are usually selectable as "resource". Hence, I think the above solution is perfectly fine, although I would suggest to make the requirement more explicit, i.e., `bifrost` and `bifrost-avx2`. As an example, the software `RAxML` uses this way of distinguishing different binaries that rely on SSE3, AVX2 etc

**Comment by winni2k** [comment] 2020-06-04 09:43
Excellent. Thanks for the input @ptrebert.

@GuillaumeHolley can you create a release of the current master branch so that I can use it in the bioconda recipe?

**Comment by winni2k** [comment] 2020-06-04 12:17
I have been reading a bit more on the march argument in gcc, and I came across these three pages that seem helpful:

1. https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html
2. https://wiki.gentoo.org/wiki/Safe_CFLAGS
3. https://wiki.gentoo.org/wiki/GCC_optimization#Optimization_FAQs

The first link is the gcc documentation on what can be supplied to the `march` flag. The second link is part of the gentoo wiki that describes safe/recommended CFLAGS that include the `march` flag to use with different CPU architectures. The third link explains why the gentoo wiki makes the recommendations it does in link 2.

Observations:
- There are a lot of CPU architectures out there that the march flag can optimize for.
- There are a lot of so-called 64 bit extensions and the set of supported extensions varies a great deal across even just intel archictectures. For example, `-march=core2` turns on the instruction sets `MMX, SSE, SSE2, SSE3 and SSSE3`, whereas `-march=skylake` turns on the instruction sets `MOVBE, MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, POPCNT, AVX, AVX2, AES, PCLMUL, FSGSBASE, RDRND, FMA, BMI, BMI2, F16C, RDSEED, ADCX, PREFETCHW, CLFLUSHOPT, XSAVEC and XSAVES`.
- From compiling bifrost on my machine it looks like `march=x84-64` supports SSE2 but not SSE3 instructions.

Given the number of instruction sets that can be turned on or off, I think it would make sense to compile code with the CPU-specific march flag `x86-64`, `core2`, and `skylake` and create a package for each of the three, and then add more packages if there is demand.

PS This SO question was useful in diagnosing which instruction sets got used during my test compilations: https://stackoverflow.com/a/50056059/528691

**Comment by winni2k** [comment] 2020-06-04 12:20
Perhaps also `sandybridge` for an architecture that supports AVX but not AVX2.

**Comment by winni2k** [comment] 2020-06-04 21:18
I had a chat on the gitter channel with the folks at bioconda, and I think the idea of having multiple bioconda packages for a single project did not go over well. Also, I find the solution proposed by jjhelmus a bit daunting.

Instead, I remembered that C/C++ code can be packaged in a python package, and I found a tool-chain (scikit-build) that allows this quite easily from a CMake project. I have created a PR (#24) that includes my first attempt at packaging bifrost in a python package. I have deployed the source-only package to pypi under the name `bifrost-src`.

So, this now allows the compilation and installation of bifrost through `pip` using the command `pip install bifrost-src --no-binary bifrost-src`. This should create a binary using `-march=native`. My PR also includes an environment.yml for installing the compilation dependencies that can't be installed through pip (zlib). Here is the environment.yml again for reference:

```
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip=20.1.1
  - zlib=1.2.11
  - pip:
    - bifrost-src
```

I think what we can do now is submit this environment.yml as a meta-package to bioconda, and this will use pip to compile bifrost on the installed machine natively.

@ptrebert can you try and see if the environment.yml works on your machines? I can get it to work on my mac and a skylake machine running debian 10.

**Comment by winni2k** [comment] 2020-06-04 21:22
Oh, I had to change the linking of the Bifrost binary to use the static library because the dynamic library was not being found by the Bifrost binary at runtime. I bet this is an RPATH issue, and RPATH issues are still on the todo list for the scikit-build project. Is it a terrible problem if we link the Bifrost binary statically instead of dynamically? I don't know CMake very well. Is there an easy way to create a CMake flag so we can link statically only for the python package?

**Comment by winni2k** [comment] 2020-06-05 18:06
An update: I tried installing the pypi version into the miniconda3 minimal docker image, and I needed the following environment.yml to get the package to install.

```
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - pip=20.1.1
  - zlib=1.2.11
  - binutils=2.32
  - gxx_linux-64=7.3.0
  - pip:
    - bifrost-src
```

**Comment by ptrebert** [comment] 2020-06-23 13:55
@winni2k 
Sorry that it took me so long to come back to this. I just tested installing Bifrost using the environment that you posted above (the one including binutils etc). It looks like this is working even on the machines that lack the AVX2 instruction set.

**Comment by GuillaumeHolley** [comment] 2020-07-07 17:27
Hey everyone,

I apologize for the delay. I am currently in holidays but as soon as I am back next week, I will make a new release for Bifrost ;) Thank you for you help!

**Comment by GuillaumeHolley** [comment] 2020-07-14 22:24
Bifrost v1.0.4 released. I will make the Brew package in the coming days.

**Comment by GuillaumeHolley** [comment] 2020-07-31 18:21
Dear @winni2k and @ptrebert,

Bifrost 1.0.4 is officially released as Bioconda and Brew packages. The Bioconda/Brew package disables native compilation so it shouldn't be an issue to install on one machine and use it on another one. Even better, the Bioconda package is now available for MacOS (for some reasons, I couldn't pass Bioconda's CI test for OSX before).

**Closed by GuillaumeHolley** 2020-07-31 18:21 UTC
Labels: bug, enhancement, suggestion
